# Generated by Django 6.0.8 on 2026-08-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('engine', models.IntegerField()),
                ('ear', models.IntegerField()),
                ('color', models.CharField()),
            ],
        ),
    ]
